export * from './lib/coreConnection.js'
export * from './lib/CoreConnectionChild.js'
export * from './lib/configManifest.js'
export * from './lib/ddpClient.js'
export * from './lib/gateway-types.js'
export * from './lib/health.js'
export * from './lib/methods.js'
export * from './lib/process.js'
export * from './lib/prometheus.js'
export * from './lib/queue.js'
export type { SubscriptionId, ParametersOfFunctionOrNever } from './lib/subscriptions.js'

// Re-export some util from shared-lib
export * from '@sofie-automation/shared-lib/dist/lib/lib.js'
export * from '@sofie-automation/shared-lib/dist/lib/stringifyError.js'
export * from '@sofie-automation/shared-lib/dist/lib/protectedString.js'
export * from '@sofie-automation/shared-lib/dist/lib/JSONBlob.js'
export * from '@sofie-automation/shared-lib/dist/lib/JSONSchemaTypes.js'
export * from '@sofie-automation/shared-lib/dist/lib/JSONSchemaUtil.js'
export { PeripheralDeviceAPIMethods } from '@sofie-automation/shared-lib/dist/peripheralDevice/methodsAPI.js'
export type { PeripheralDeviceForDevice } from '@sofie-automation/shared-lib/dist/core/model/peripheralDevice.js'
export type { PeripheralDeviceCommand } from '@sofie-automation/shared-lib/dist/core/model/PeripheralDeviceCommand.js'
export { StatusCode } from '@sofie-automation/shared-lib/dist/lib/status.js'
export * as PeripheralDeviceAPI from '@sofie-automation/shared-lib/dist/peripheralDevice/peripheralDeviceAPI.js'
export type { PeripheralDeviceId, StudioId } from '@sofie-automation/shared-lib/dist/core/model/Ids.js'
export * from '@sofie-automation/shared-lib/dist/pubsub/peripheralDevice.js'
